# Generated by Django 4.2.7 on 2023-11-27 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_device_user_casual_leave_user_emergency_leave_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leavestatus",
            name="reason",
        ),
        migrations.AlterField(
            model_name="leavestatus",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="casual_leave",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="user",
            name="emergency_leave",
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
