# Generated by Django 4.2.7 on 2023-11-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_leavestatus_reason_alter_leavestatus_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="device",
            field=models.TextField(blank=True, null=True),
        ),
    ]
